Working into the contact form and changing README file
nimplay/Microverse_Portfolio pull request #4
Opened 2022-05-30 22:06 UTC by nimplay

Summary:

We create tha contact form and add new information about mu partner in README file.

2022-05-30 23:26 UTC, cwaku reviewed
Hi @nimplay

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🔴 

You have submitted a project, that I cannot perform a thorough review on the PR. I only see changes to README and not the other files. Kindly create a new PR and push the commits again. To prevent this in the future, please always confirm that changes are visible when you click on "Files changes"

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-05-31 11:59 UTC, nimplay commented
Summary:
last week forward the contact form for that reason did not have many changes to make. Although I did notice that I had not added the "inter" font nor had I set the character limit in the name box and had not activated the requirement for the form.

2022-05-31 12:09 UTC, m05e5 requested changes
Hi @nimplay , 

Good job so far. I really like what you did!
There are some issues that you still need to work on to go to the next project but you are almost there!
![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)


## Highlights


## Required Changes ♻️
* You really did a great job but there are some features you need to improve

- [ ] _**Please check the comments below**_

_I'm sure you can do it just keep it up_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_@m05e5_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-31 12:09 UTC, m05e5 commented on index.html
>            type="text"
- [ ] Great job but i recommend using `type="email"` for the email field

2022-05-31 12:09 UTC, m05e5 commented on index.html
>        <form class="contactform">
- [ ] as part of the requirements, your form should uses the action and method attribute to integrate with [formspree service](https://formspree.io/html)

2022-05-31 14:29 UTC, NATASHA-ct reviewed
- [ ] Nothing to say, you did well . Great Job.

2022-05-31 18:22 UTC, Ginohmk requested changes
Hi @nimplay , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![keep-trying-youre-almost-there](https://user-images.githubusercontent.com/67087664/169483884-c624db70-793d-42be-8ebe-afef6a1cd5c3.gif)

 ## Highlights
- Linters passed
- Clean code :+1: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-31 18:22 UTC, Ginohmk commented on index.html
>          <input class="csubmit" type="submit" value="Get in touch" />
- Please add button interaction as it is shown in the Figma, such as hover, active (when it's pressed), disabled and enable (default state)

2022-05-31 21:24 UTC, Ginohmk approved these changes
Hi @nimplay , 

# STATUS: APPROVED 🟢

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## TO HIGHLIGHT: 
- Your project is professional 💯 
- Your repo is professional 💯 
- Well structured files 💯 
- You set up linter files and no errors. 💯 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-31 21:29 UTC, merged